# Site settings
title: Ke Li
description: 'Business Card Page'
url: 'https://github.com/likeeeice'
baseurl: ''
profilepic: '/images/profile.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Ke Li'
  email: likeeeice@gmail.com
  twitter_username: None # 
#  facebook_username: joshgerdes
  github_username:  likeeeice
  linkedin_username:  李柯
  meetup_name: None #

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
